[package]
name = "lalrpop"
version = "0.1.0"
authors = ["Kris Jordan <kris@cs.unc.edu>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
lalrpop-util = "0.16.3"
regex = "0.2.1"
