use std::str::FromStr;

grammar;

pub Expr: i32 = {
    <l:Expr> "+" <r:Factor> => l + r,
    <l:Expr> "-" <r:Factor> => l - r,
    <f:Factor>              => f,
}

Factor: i32 = {
    <l:Factor> "*" <r:Term> => l * r,
    <l:Factor> "/" <r:Term> => l / r,
    <t:Term>                => t,
}

Term: i32 = {
    <n:Num>                 => n,
    "(" <e:Expr> ")"        => e,
};

Num: i32 = { 
    r"[0-9]+" => i32::from_str(<>).unwrap(),
}
